name: mealo
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.6.0

environment:
  sdk: '>=3.0.0 <4.0.0'

# Globals for packages which share the same version
isar_version: &isar_version 4.0.0-dev.14

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Base components
  base_components:
    git:
      url: https://github.com/Kounex/base_components.git
      ref: main

  # Unique identifier for our models
  uuid: ^3.0.7

  # Immutability
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0

  # JSON parser and serializer
  # crimson: ^0.2.1

  # State management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Local storage
  isar: *isar_version
  isar_flutter_libs: *isar_version

  shared_preferences: ^2.0.17

  # Navigator 2.0
  beamer: ^1.5.3

  # Some fancy utility functions for collections
  collection: ^1.17.0

  # Enable camera access and handling
  camera: ^0.10.3

  # Enable selecting files
  file_picker: ^10.2.2

  # HTTP client
  dio: ^5.1.1

  # Some hashing functions
  crypto: ^3.0.2

  # Work with paths / directories
  path_provider: ^2.0.14

  # UI
  # Consistent theming
  flex_color_scheme: ^8.2.0

  # Power up slivers
  sliver_tools: ^0.2.8

  # Animations
  flutter_staggered_animations: ^1.1.1

  # Microsoft icons pack
  fluentui_system_icons: ^1.1.190

  # Adjust text size correctly
  auto_size_text: ^3.0.0 

  # Powered-up animations
  flutter_animate: ^4.0.0

  # Pre-built color picker because it is a pain in the ass to do on my own
  flutter_colorpicker: ^1.0.3

  # App Icon
  flutter_launcher_icons: ^0.14.4

  # Native Splash Screen for initializing
  flutter_native_splash: ^2.4.6

  # Reorder everything
  reorderables: ^0.6.0
  reorderable_grid:
    git:
      url: https://github.com/Kounex/reorderable_grid.git
      ref: drag-background

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:
  custom_lint:
  build_runner:

  # analyzer: ^5.5.0
  # analyzer_plugin: ^0.11.2
  riverpod_lint: ^2.6.1

  # Generator stuff
  # isar_generator: *isar_version

  riverpod_generator: ^2.6.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
